label variable HIV_test "HIV test "
label variable syphilis_test "Syphilis test "
label variable malaria_test "Malaria test "
label variable malaria_pills "Malaria pills "
label variable malaria_net "Received malaria net "
label variable tetanus "Tetanus vac. "
label variable blood_pressure "Blood pressure "
label variable blood_test "Blood sample "
label variable urine "Urine sample "
label variable weight "Weight "
label variable examine_belly "Examine belly "
label variable height "Height "
label variable uterine_height "Uterine height "
label variable folic_acid "Folic acid "
label variable ask_history "Ask preg. history "
label variable delivery_place "Disc. delivery plan "
label variable delivery_plan "Disc. delivery place "
label variable estimated "Estimated delivery date "
label variable complications_sign "Disc complications sign "
label variable nutrition "Nutrition advice "
label variable questions "Answer your questions "

label variable proc_index "% procedures "
